version: "3.9"

services:
  app:
    build: .
    container_name: go-gin-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always

# Optional local DB for dev/test
  db:
    image: mysql:8.0
    container_name: my-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
